Pytorch Tutorial
Tensors Basics
A tensor is a generalization of vectors and matrices and is easily understood as a multidimensional array.It is a term and set of techniques known in machine learning in the training and operation of deep learning models can be described in terms of tensors. In many cases tensors are used as a replacement for NumPy to use the power of GPUs.

Tensors are a type of data structure used in linear algebra, and like vectors and matrices, you can calculate arithmetic operations with tensors.

In [1]:
import torch

In [2]:
torch.__version__

'1.5.1'

In [3]:
import numpy as np

## First create the list then convert it nupmy array

In [4]:
lst = [2,4,6,7,8,9,10]
np_arr = np.array(lst)

In [5]:
lst

[2, 4, 6, 7, 8, 9, 10]

In [6]:
np_arr

array([ 2,  4,  6,  7,  8,  9, 10])

In [7]:
np_arr.dtype

dtype('int64')

## Convert Numpy to Pytorch Tensors

In [8]:
tensors = torch.from_numpy(np_arr)

In [9]:
tensors

tensor([ 2,  4,  6,  7,  8,  9, 10])

In [10]:
# write the tensor value until 3 index
tensors[:3]

tensor([2, 4, 6])

In [11]:
# only get the forth index of tensor
tensors[4]

tensor(8)

In [12]:
# get value of between the 2 and 6 indexes
tensors[2:6]

tensor([6, 7, 8, 9])

In [13]:
# disadvantage of from_numpy. Still array and tensor share same memory location, for this reason manuplation effect 
# both values
tensors[2] = 150

In [14]:
# we can see the sencond index of np_arr changed, when ı am assigning the new value for tensors
np_arr

array([  2,   4, 150,   7,   8,   9,  10])

In [15]:
tensors

tensor([  2,   4, 150,   7,   8,   9,  10])

In [16]:
## prevent this error by using torch.tensor function
tensor_arr = torch.tensor(np_arr)
tensor_arr

tensor([  2,   4, 150,   7,   8,   9,  10])

In [17]:
tensor_arr[4] = 880

In [18]:
tensor_arr

tensor([  2,   4, 150,   7, 880,   9,  10])

In [19]:
np_arr

array([  2,   4, 150,   7,   8,   9,  10])

In [20]:
## the other way to create the new tensor from zeros
## the native torch function do this
torch.zeros(2,3,dtype=torch.float64)

tensor([[0., 0., 0.],
        [0., 0., 0.]], dtype=torch.float64)

In [21]:
torch.ones(6,9,dtype=torch.int64)

tensor([[1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [22]:
## Arithmetic Operation of Tensor
a = torch.tensor([3,4,4,5],dtype=torch.float64)
b = torch.tensor([4,8,7,9],dtype=torch.float64)

a = a + b

In [23]:
print(a)

tensor([ 7., 12., 11., 14.], dtype=torch.float64)


In [33]:
## other method for summatio
torch.add(a,b)

tensor([11., 20., 18., 23.], dtype=torch.float64)

In [29]:
## numpy = np can arrange list and matrix with arange 
## reshape func return the matrix given form for example (5,3) now
new_np_array=np.arange(0,15).reshape(5,3)

In [42]:
new_np_array = torch.tensor(new_np_array,dtype=torch.float)

In [43]:
second_array = np.arange(0,15).reshape(5,3)

In [46]:
second_array = torch.tensor(second_array, dtype=torch.float)

In [ ]:
# basicly add function output

tensor([[ 0.,  2.,  4.],
        [ 6.,  8., 10.],
        [12., 14., 16.],
        [18., 20., 22.],
        [24., 26., 28.]])
# then sum() function get the total value.

In [50]:
torch.add(new_np_array,second_array).sum()

tensor(210.)

## Dot Products and Mult Operations

In [51]:
x = torch.tensor([5,8,9], dtype = torch.float)
y = torch.tensor([8,9,6], dtype = torch.float)

In [53]:
# multiple the this two matrix
# that s function only multp. two vector
torch.mul(x,y)

tensor([40., 72., 54.])

In [59]:
z = torch.tensor([8,9,7,4], dtype = torch.int32)

In [60]:
# this operation not valid "The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0"
torch.mul(x,z)

RuntimeError: The size of tensor a (3) must match the size of tensor b (4) at non-singleton dimension 0

In [61]:
# 5*8 + 8*9 + 6*9
x.dot(y)

tensor(166.)

#### MAtrix Multiplication

In [64]:
# we can define the matrix using torch.tensor
mat_x = torch.tensor([[1,2,3],[4,5,6]], dtype = torch.float)
mat_y = torch.tensor([[1,2],[4,8],[7,8]], dtype = torch.float)

In [65]:
torch.matmul(mat_x,mat_y)

tensor([[30., 42.],
        [66., 96.]])

In [66]:
torch.mm(mat_x,mat_y)

tensor([[30., 42.],
        [66., 96.]])